development:
  app_name: "Sample_app"

links:
  rails_home: "http://www.railstutorial.org/"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  gravatar: "https://gravatar.com/emails"

digits:
  digit_0: 0
  digit_5: 5
  digit_6: 6
  digit_7: 7
  digit_14: 14
  digit_20: 20

pagy:
  items: 10
  books: 20

email:
  from_address: "noreply@example.com"

user_mailer:
  host: localhost:3000
  protocol: http
images:
  banner_image: "banner.jpg"
  default_cover: "default_cover.jpg"
  default_author: "default_author.jpg"
  rating_and_reviews_avatar: "Rating&comment_user_image.jpg"

mailer:
  expire_hour: 2

sizes:
  size_80: 80

datetime_formats:
  default: "%d-%m-%Y %H:%M"

date_format:
  long: "%B %d, %Y"
user:
  default_avatar: "user/default_avatar.png"
  avatar_size: "150x150"
book:
  cover_image_size: "60x80"
  default_cover_image: "book/default_book.png"

books:
  title_truncated_length: 50
  category_truncated_length: 40
  author_truncated_length: 30
  publisher_truncated_length: 30
  minimum_available_copies: 0
